### ISSUE TITLE
Performing a search without first logging in results in a stack dump

### ISSUE THREAD

**Issue by usask-rc** [globus/globus-search-cli#3]
$ globus-search query my-index-id data

Traceback (most recent call last):
  File "/usr/local/bin/globus-search", line 8, in <module>
    sys.exit(cli_root())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/globus_search_cli/parsing/click_wrappers.py", line 121, in invoke
    return super(GlobusCommandGroup, self).invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/globus_search_cli/commands/query.py", line 34, in query_func
    search_client = get_search_client()
  File "/usr/local/lib/python3.5/dist-packages/globus_search_cli/config.py", line 68, in get_search_client
    searchdata = maybe_existing[SEARCH_RESOURCE_SERVER]
KeyError: 'search.api.globus.org'

$ globus-search -v
globus-search, version 0.4.0

After login, the command works fine.

**Comment by sirosen** [comment]
Thanks for reporting! It's definitely a bug. It's supposed to fallback to an unauthenticated search in this scenario. I bet I can put out a patch today.

**Comment by sirosen** [comment]
I just released v0.4.1 , so the fix should now be available from pypi.
